# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PowerAtom
                                 A QGIS plugin
 INSPIRE Atom Client
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-19
        copyright            : (C) 2026 by Łukasz Świątek
        email                : lukasz.swiatek1996@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PowerAtom class from file PowerAtom.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .power_atom import PowerAtom
    return PowerAtom(iface)
